language: python
install:
  - pip install tox
  - pip install flake8
matrix:
  include:
    - python: "2.7"
      env: TOX_ENVS=py27-django111
    - python: "3.4"
      env: TOX_ENVS=py34-django111,py34-django20
    - python: "3.5"
      env: TOX_ENVS=py35-django111,py35-django20,py35-django20,py35-django21
    - python: "3.6"
      env: TOX_ENVS=py36-django111,py36-django20,py36-django21
    - python: "3.6"
      dist: xenial
      sudo: true
      env: TOX_ENVS=py36-django22
    - python: "3.7"
      env: TOX_ENVS=py37-django20,py37-django21,py37-django22
      dist: xenial
      sudo: true
before_script:
  - flake8 .
script:
  - tox -e $TOX_ENVS
deploy:
  provider: pypi
  user: james.mcmahon
  password: testpasswordfortravis
  on:
    tags: true
    repo: James1345/django-rest-knox
  only:
    - master
  distributions: "sdist bdist_wheel"
git:
  depth: false
